### ISSUE TITLE
Use this code for learning purpose

### ISSUE THREAD

**Issue by Sosthene00** [mikejquinn/rust-tetris#3]
Hi, not really an issue, I'm teaching a Rust beginner's course and wanted to use Tetris as material, I tried a couple other implementations in Rust out there and even got fairly far writing my own, but I found out that yours was very suitable for what I was trying to do.  

I intend to first use it as is as an example to explain basic concepts and fiddle around, and then let my student try to improve on it. I started to write another repo and will make it public soon.

I just wanted to thank you and make sure that you're okay with that.

**Comment by mikejquinn** [comment]
Not a problem, go for it! Note that I wrote this years ago though and haven't revisited it (or rust) since then. It likely needs updates to conform to modern rust.

**Comment by Sosthene00** [comment]
Yes actually updating a slightly outdated code makes a nice first assignment for students :smile:
